config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
  get 'comments/show'
  get 'users/index'
  devise_for :users
  resources :articles do
    member do
  
         put 'toggle_like', to: 'articles#toggle_like'
    end
  
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :users do
    member do
      patch :approve
      patch :rejected
      patch :pending
      post 'send_friend_request', to: 'friendships#create'
    end

    collection do
      get 'friend_requests', to: 'users#friend_requests'  # Route for displaying pending friend requests
       get 'admin', to: 'users#admin'
   
    end
  end

  resources :friendships, only: [:create, :update, :destroy] do
    member do
      patch 'accept', to: 'friendships#update', defaults: { status: 'accept' }
      patch 'reject', to: 'friendships#update', defaults: { status: 'reject' }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
root "articles#index"



get 'drafts', to: 'articles#drafts', as: 'drafts'
get 'cancel', to: 'users#cancel', as: 'cancel'
get 'users/:id/friends', to: 'users#friends', as: 'user_friends'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>

    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    

  </head>

  <body>
  <% if user_signed_in? %>
  <div class="d-flex justify-content-end align-items-center mb-3">
    <!-- User info -->
    <p class="mb-0 me-3">
    Signed in as 
    <span class="fw-bold text-danger">
      <%= link_to current_user.first_name, user_path(current_user) %>
    </span> 
    <strong class="text-danger">
      (<%= current_user.roles.any? ? current_user.roles.pluck(:name).join(", ") : "user" %>)
    </strong>
  </p>

    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger', form: { data: { turbo_confirm: "Are you sure?" } } %>
  </div>
 <% if current_user.has_role? :admin %>
  <div class="mb-0 d-grid justify-content-end align-items-center ">
  <p>You have <strong><%= @admin_count %></strong> pending approvals.</p>
  <%= link_to 'Go to Admin Page', admin_users_path, class: 'btn btn-secondary' %>
</div>
<% end %>
<% end %>

   <%= yield %>
  </body>
</html>